version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pa_database
    environment:
      POSTGRES_DB: dashboard_pa
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Pa@Aerobase15243
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
